databases:
  - name: postgres
    ipAllowList: []
    databaseName: mecca_rewards
    user: mecca_rewards

services:
  - type: web
    name: mecca_rewards
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
